const a = "A";
export const rows = [
  {
    no: 1,
    lastName: "たなか",
    firstName: "はると",
    gender: "男子",
    grade: 3,
    class: 2,
    lang: 82,
    arith: 95,
    science: 78,
    details: {
      birthday: "2022-09-12",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 2,
    lastName: "さとう",
    firstName: "あおい",
    gender: "女子",
    grade: 4,
    class: 1,
    lang: 67,
    arith: 73,
    science: 85,
    details: {
      birthday: "2021-03-25",
      bloodtype: "O",
      club: "バレー",
    },
  },
  {
    no: 3,
    lastName: "すずき",
    firstName: "ゆうた",
    gender: "男子",
    grade: 1010,
    class: 3,
    lang: 43,
    arith: 50,
    science: 93,
  },
  {
    no: 4,
    lastName: "わたなべ",
    firstName: "みお",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 79,
    arith: 84,
    science: 43,
    details: {
      birthday: "2023-09-30",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 5,
    lastName: "やまもと",
    firstName: "ひなた",
    gender: "女子",
    grade: 4,
    class: 2,
    lang: 88,
    arith: 92,
    science: 89,
    details: {
      birthday: "2021-05-17",
      bloodtype: "A",
      club: "バレー",
    },
  },
  {
    no: 6,
    lastName: "なかむら",
    firstName: "りく",
    gender: "男子",
    grade: 6,
    class: 1,
    lang: 1,
    arith: 300,
    science: 12,
    details: {
      birthday: "2019-01-22",
      bloodtype: "O",
      club: "サッカー",
    },
  },
  {
    no: 7,
    lastName: "こばやし",
    firstName: "さくら",
    gender: "女子",
    grade: 3,
    class: 3,
    lang: 76,
    arith: 81,
    science: 74,
  },
  {
    no: 8,
    lastName: "きむら",
    firstName: "そうた",
    gender: "男子",
    grade: 1,
    class: 2,
    lang: 62,
    arith: 69,
    science: 999,
    details: {
      birthday: "2024-08-19",
      bloodtype: "AB",
      club: "野球",
    },
  },
  {
    no: 9,
    lastName: "はやし",
    firstName: "あかり",
    gender: "女子",
    grade: 5,
    class: 4,
    lang: 87,
    arith: 83,
    science: 90,
    details: {
      birthday: "2020-06-14",
      bloodtype: "A",
      club: "バレー",
    },
  },
  {
    no: 10,
    lastName: "さいとう",
    firstName: "ゆうき",
    gender: "男子",
    grade: 2,
    class: 1,
    lang: 67,
    arith: 45,
    science: 53,
    details: {
      birthday: "2023-10-28",
      bloodtype: "O",
      club: "サッカー",
    },
  },
  {
    no: 11,
    lastName: "いとう",
    firstName: "れん",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 79,
    arith: 88,
    science: 92,
    details: {
      birthday: "2020-05-17",
      bloodtype: "B",
      club: "野球",
    },
  },
  {
    no: 12,
    lastName: "かとう",
    firstName: "みゆき",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 95,
    arith: 72,
    science: 83,
    details: {
      birthday: "2023-11-30",
      bloodtype: "A",
      club: "なし",
    },
  },
  {
    no: 13,
    lastName: "やまだ",
    firstName: "たいち",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 68,
    arith: 89,
    science: 76,
  },
  {
    no: 14,
    lastName: "おの",
    firstName: "はな",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 91,
    arith: 85,
    science: 94,
    details: {
      birthday: "2019-03-08",
      bloodtype: "AB",
      club: "バレー",
    },
  },
  {
    no: 15,
    lastName: "たけうち",
    firstName: "ゆうすけ",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 73,
    arith: 78,
    science: 86,
    details: {
      birthday: "2021-09-14",
      bloodtype: "A",
      club: "野球",
    },
  },
  {
    no: 16,
    lastName: "なかの",
    firstName: "あやか",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 87,
    arith: 93,
    science: 79,
    details: {
      birthday: "2024-12-01",
      bloodtype: "B",
      club: "なし",
    },
  },
  {
    no: 17,
    lastName: "まつおか",
    firstName: "こうた",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 82,
    arith: 75,
    science: 88,
  },
  {
    no: 18,
    lastName: "ふじわら",
    firstName: "みく",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 94,
    arith: 87,
    science: 91,
  },
  {
    no: 19,
    lastName: "おおつか",
    firstName: "はると",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 76,
    arith: 81,
    science: 84,
    details: {
      birthday: "2022-10-11",
      bloodtype: "AB",
      club: "野球",
    },
  },
  {
    no: 20,
    lastName: "あべ",
    firstName: "さくら",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 89,
    arith: 96,
    science: 82,
    details: {
      birthday: "2019-04-25",
      bloodtype: "B",
      club: "なし",
    },
  },
  {
    no: 21,
    lastName: "きくち",
    firstName: "りょう",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 71,
    arith: 83,
    science: 90,
    details: {
      birthday: "2021-08-07",
      bloodtype: "O",
      club: "サッカー",
    },
  },
  {
    no: 22,
    lastName: "いわさき",
    firstName: "あおい",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 93,
    arith: 79,
    science: 85,
  },
  {
    no: 23,
    lastName: "みやざき",
    firstName: "だいき",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 78,
    arith: 92,
    science: 87,
    details: {
      birthday: "2020-11-29",
      bloodtype: "B",
      club: "野球",
    },
  },
  {
    no: 24,
    lastName: "おかだ",
    firstName: "ゆうな",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 86,
    arith: 88,
    science: 93,
    details: {
      birthday: "2023-05-03",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 25,
    lastName: "はやし",
    firstName: "そうた",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 74,
    arith: 80,
    science: 89,
  },
  {
    no: 26,
    lastName: "もり",
    firstName: "ひなた",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 92,
    arith: 95,
    science: 81,
  },
  {
    no: 27,
    lastName: "いのうえ",
    firstName: "ゆうと",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 77,
    arith: 84,
    science: 91,
    details: {
      birthday: "2021-12-17",
      bloodtype: "B",
      club: "野球",
    },
  },
  {
    no: 28,
    lastName: "こんどう",
    firstName: "まい",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 90,
    arith: 76,
    science: 88,
    details: {
      birthday: "2024-07-05",
      bloodtype: "O",
      club: "なし",
    },
  },
  {
    no: 29,
    lastName: "おおの",
    firstName: "けんた",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 75,
    arith: 91,
    science: 83,
    details: {
      birthday: "2020-01-28",
      bloodtype: "AB",
      club: "サッカー",
    },
  },
  {
    no: 30,
    lastName: "いしだ",
    firstName: "りこ",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 88,
    arith: 82,
    science: 94,
    details: {
      birthday: "2023-10-12",
      bloodtype: "A",
      club: "バレー",
    },
  },
  {
    no: 31,
    lastName: "さいとう",
    firstName: "ひろき",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 72,
    arith: 87,
    science: 80,
    details: {
      birthday: "2022-04-06",
      bloodtype: "B",
      club: "野球",
    },
  },
  {
    no: 32,
    lastName: "あらき",
    firstName: "なな",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 95,
    arith: 89,
    science: 86,
  },
  {
    no: 33,
    lastName: "あさの",
    firstName: "りく",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 79,
    arith: 93,
    science: 85,
    details: {
      birthday: "2021-06-11",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 34,
    lastName: "たかはし",
    firstName: "みお",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 91,
    arith: 78,
    science: 92,
    details: {
      birthday: "2024-02-27",
      bloodtype: "AB",
      club: "バレー",
    },
  },
  {
    no: 35,
    lastName: "やまぐち",
    firstName: "たくみ",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 76,
    arith: 85,
    science: 89,
    details: {
      birthday: "2020-11-14",
      bloodtype: "B",
      club: "野球",
    },
  },
  {
    no: 36,
    lastName: "なかやま",
    firstName: "あかり",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 87,
    arith: 94,
    science: 81,
  },
  {
    no: 37,
    lastName: "まつもと",
    firstName: "かずき",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 73,
    arith: 80,
    science: 88,
    details: {
      birthday: "2022-09-18",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 38,
    lastName: "こばやし",
    firstName: "ゆい",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 94,
    arith: 86,
    science: 93,
    details: {
      birthday: "2019-07-02",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 39,
    lastName: "きむら",
    firstName: "しょうた",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 78,
    arith: 91,
    science: 84,
    details: {
      birthday: "2021-01-09",
      bloodtype: "AB",
      club: "野球",
    },
  },
  {
    no: 40,
    lastName: "さとう",
    firstName: "はるか",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 89,
    arith: 77,
    science: 90,
    details: {
      birthday: "2024-10-24",
      bloodtype: "O",
      club: "なし",
    },
  },
  {
    no: 41,
    lastName: "かわの",
    firstName: "そうすけ",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 75,
    arith: 88,
    science: 82,
    details: {
      birthday: "2020-04-15",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 42,
    lastName: "よしだ",
    firstName: "みゆ",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 93,
    arith: 83,
    science: 95,
    details: {
      birthday: "2023-12-07",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 43,
    lastName: "さの",
    firstName: "りょうた",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 71,
    arith: 89,
    science: 86,
    details: {
      birthday: "2022-08-21",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 44,
    lastName: "かとう",
    firstName: "あやね",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 96,
    arith: 92,
    science: 87,
    details: {
      birthday: "2019-03-13",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 45,
    lastName: "なかむら",
    firstName: "こうき",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 77,
    arith: 85,
    science: 91,
  },
  {
    no: 46,
    lastName: "こんどう",
    firstName: "さくら",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 92,
    arith: 79,
    science: 88,
    details: {
      birthday: "2024-05-17",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 47,
    lastName: "おおつか",
    firstName: "ゆうと",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 74,
    arith: 90,
    science: 83,
    details: {
      birthday: "2020-02-03",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 48,
    lastName: "いしかわ",
    firstName: "あおい",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 88,
    arith: 93,
    science: 80,
    details: {
      birthday: "2023-09-26",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 49,
    lastName: "たなか",
    firstName: "はると",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 79,
    arith: 82,
    science: 94,
    details: {
      birthday: "2022-07-11",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 50,
    lastName: "ふじた",
    firstName: "みく",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 95,
    arith: 87,
    science: 89,
    details: {
      birthday: "2019-01-22",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 51,
    lastName: "やまもと",
    firstName: "りく",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 72,
    arith: 88,
    science: 85,
    details: {
      birthday: "2021-10-09",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 52,
    lastName: "すずき",
    firstName: "ひなた",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 91,
    arith: 76,
    science: 92,
    details: {
      birthday: "2024-06-14",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 53,
    lastName: "みやざき",
    firstName: "そうた",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 76,
    arith: 94,
    science: 81,
  },
  {
    no: 54,
    lastName: "いとう",
    firstName: "ゆい",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 89,
    arith: 85,
    science: 93,
    details: {
      birthday: "2023-11-05",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 55,
    lastName: "きくち",
    firstName: "たくみ",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 73,
    arith: 91,
    science: 87,
    details: {
      birthday: "2022-08-18",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 56,
    lastName: "さとう",
    firstName: "あかり",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 94,
    arith: 78,
    science: 90,
  },
  {
    no: 57,
    lastName: "たけうち",
    firstName: "ゆうすけ",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 75,
    arith: 89,
    science: 84,
    details: {
      birthday: "2021-12-21",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 58,
    lastName: "なかの",
    firstName: "まい",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 90,
    arith: 83,
    science: 95,
  },
  {
    no: 59,
    lastName: "はやし",
    firstName: "けんた",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 78,
    arith: 92,
    science: 86,
    details: {
      birthday: "2020-01-15",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 60,
    lastName: "あべ",
    firstName: "さくら",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 93,
    arith: 77,
    science: 89,
  },
  {
    no: 61,
    lastName: "おかだ",
    firstName: "ゆうと",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 71,
    arith: 86,
    science: 82,
    details: {
      birthday: "2022-05-13",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 62,
    lastName: "もり",
    firstName: "あおい",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 96,
    arith: 90,
    science: 94,
    details: {
      birthday: "2019-02-28",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 63,
    lastName: "いのうえ",
    firstName: "そうた",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 77,
    arith: 84,
    science: 88,
    details: {
      birthday: "2021-11-11",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 64,
    lastName: "かわの",
    firstName: "ゆうな",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 92,
    arith: 79,
    science: 91,
    details: {
      birthday: "2024-08-05",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 65,
    lastName: "よしだ",
    firstName: "りく",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 74,
    arith: 93,
    science: 85,
    details: {
      birthday: "2020-01-19",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 66,
    lastName: "さの",
    firstName: "みお",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 89,
    arith: 81,
    science: 93,
    details: {
      birthday: "2023-09-24",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 67,
    lastName: "かとう",
    firstName: "はると",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 76,
    arith: 87,
    science: 80,
  },
  {
    no: 68,
    lastName: "なかむら",
    firstName: "ひなた",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 95,
    arith: 92,
    science: 88,
    details: {
      birthday: "2019-03-16",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 69,
    lastName: "こんどう",
    firstName: "ゆうき",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 73,
    arith: 85,
    science: 94,
    details: {
      birthday: "2021-10-02",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 70,
    lastName: "おおつか",
    firstName: "さき",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 91,
    arith: 78,
    science: 86,
  },
  {
    no: 71,
    lastName: "いしかわ",
    firstName: "こうた",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 75,
    arith: 90,
    science: 82,
    details: {
      birthday: "2020-12-29",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 72,
    lastName: "たなか",
    firstName: "ゆい",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 88,
    arith: 93,
    science: 89,
    details: {
      birthday: "2023-07-23",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 73,
    lastName: "ふじた",
    firstName: "そうすけ",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 72,
    arith: 82,
    science: 95,
    details: {
      birthday: "2022-02-08",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 74,
    lastName: "やまもと",
    firstName: "あかり",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 94,
    arith: 87,
    science: 91,
    details: {
      birthday: "2019-08-14",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 75,
    lastName: "すずき",
    firstName: "たくみ",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 77,
    arith: 89,
    science: 84,
    details: {
      birthday: "2021-05-30",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 76,
    lastName: "みやざき",
    firstName: "まい",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 90,
    arith: 76,
    science: 93,
  },
  {
    no: 77,
    lastName: "いとう",
    firstName: "りく",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 74,
    arith: 91,
    science: 87,
  },
  {
    no: 78,
    lastName: "きくち",
    firstName: "さくら",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 93,
    arith: 84,
    science: 90,
    details: {
      birthday: "2023-01-09",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 79,
    lastName: "さとう",
    firstName: "ゆうた",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 71,
    arith: 88,
    science: 83,
    details: {
      birthday: "2022-09-20",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 80,
    lastName: "たけうち",
    firstName: "あおい",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 96,
    arith: 92,
    science: 89,
    details: {
      birthday: "2019-04-03",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 81,
    lastName: "なかの",
    firstName: "はると",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 75,
    arith: 85,
    science: 91,
    details: {
      birthday: "2021-11-28",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 82,
    lastName: "はやし",
    firstName: "みゆ",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 89,
    arith: 79,
    science: 94,
  },
  {
    no: 83,
    lastName: "あべ",
    firstName: "りょうた",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 73,
    arith: 90,
    science: 86,
    details: {
      birthday: "2020-02-19",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 84,
    lastName: "おかだ",
    firstName: "あやね",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 92,
    arith: 83,
    science: 88,
    details: {
      birthday: "2023-10-07",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 85,
    lastName: "もり",
    firstName: "こうき",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 77,
    arith: 87,
    science: 82,
    details: {
      birthday: "2022-05-22",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 86,
    lastName: "いのうえ",
    firstName: "ひなた",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 95,
    arith: 91,
    science: 93,
    details: {
      birthday: "2019-01-11",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 87,
    lastName: "かわの",
    firstName: "ゆうと",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 74,
    arith: 84,
    science: 90,
    details: {
      birthday: "2021-08-30",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 88,
    lastName: "よしだ",
    firstName: "さくら",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 91,
    arith: 78,
    science: 85,
  },
  {
    no: 89,
    lastName: "さの",
    firstName: "そうた",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 76,
    arith: 93,
    science: 87,
    details: {
      birthday: "2020-03-02",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 90,
    lastName: "かとう",
    firstName: "あおい",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 88,
    arith: 82,
    science: 94,
  },
  {
    no: 91,
    lastName: "なかむら",
    firstName: "だいき",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 72,
    arith: 89,
    science: 81,
    details: {
      birthday: "2022-12-05",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 92,
    lastName: "こんどう",
    firstName: "ゆうな",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 94,
    arith: 86,
    science: 92,
    details: {
      birthday: "2019-04-28",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 93,
    lastName: "おおつか",
    firstName: "りく",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 75,
    arith: 90,
    science: 83,
  },
  {
    no: 94,
    lastName: "いしかわ",
    firstName: "みお",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 93,
    arith: 77,
    science: 89,
    details: {
      birthday: "2024-06-30",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 95,
    lastName: "たなか",
    firstName: "たくみ",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 71,
    arith: 88,
    science: 95,
    details: {
      birthday: "2020-01-24",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 96,
    lastName: "ふじた",
    firstName: "あかり",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 90,
    arith: 84,
    science: 86,
  },
  {
    no: 97,
    lastName: "やまもと",
    firstName: "ゆうすけ",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 78,
    arith: 92,
    science: 80,
    details: {
      birthday: "2022-07-17",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 98,
    lastName: "すずき",
    firstName: "まい",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 96,
    arith: 85,
    science: 91,
    details: {
      birthday: "2019-02-04",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 99,
    lastName: "みやざき",
    firstName: "けんた",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 73,
    arith: 81,
    science: 87,
    details: {
      birthday: "2021-09-26",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 100,
    lastName: "いとう",
    firstName: "さき",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 89,
    arith: 93,
    science: 84,
    details: {
      birthday: "2024-05-12",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 101,
    lastName: "きくち",
    firstName: "はると",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 76,
    arith: 87,
    science: 92,
    details: {
      birthday: "2020-01-08",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 102,
    lastName: "さとう",
    firstName: "ゆい",
    gender: "女子",
    grade: 2,
    class: 2,
    lang: 94,
    arith: 80,
    science: 88,
    details: {
      birthday: "2023-08-21",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 103,
    lastName: "たけうち",
    firstName: "そうた",
    gender: "男子",
    grade: 3,
    class: 3,
    lang: 72,
    arith: 91,
    science: 85,
    details: {
      birthday: "2022-04-15",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 104,
    lastName: "なかの",
    firstName: "あおい",
    gender: "女子",
    grade: 6,
    class: 4,
    lang: 95,
    arith: 86,
    science: 90,
    details: {
      birthday: "2019-12-29",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 105,
    lastName: "はやし",
    firstName: "ゆうき",
    gender: "男子",
    grade: 4,
    class: 1,
    lang: 77,
    arith: 83,
    science: 93,
    details: {
      birthday: "2021-09-07",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 106,
    lastName: "あべ",
    firstName: "みゆ",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 91,
    arith: 89,
    science: 82,
    details: {
      birthday: "2024-03-24",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 107,
    lastName: "おかだ",
    firstName: "りょうた",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 74,
    arith: 92,
    science: 87,
    details: {
      birthday: "2020-11-11",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 108,
    lastName: "もり",
    firstName: "はるか",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 88,
    arith: 78,
    science: 94,
    details: {
      birthday: "2023-07-03",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 109,
    lastName: "いのうえ",
    firstName: "こうき",
    gender: "男子",
    grade: 3,
    class: 1,
    lang: 75,
    arith: 90,
    science: 81,
    details: {
      birthday: "2022-04-19",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 110,
    lastName: "かわの",
    firstName: "さくら",
    gender: "女子",
    grade: 6,
    class: 2,
    lang: 93,
    arith: 85,
    science: 89,
    details: {
      birthday: "2019-12-06",
      bloodtype: "B",
      club: "バレー",
    },
  },
  {
    no: 111,
    lastName: "よしだ",
    firstName: "そうすけ",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 71,
    arith: 87,
    science: 95,
    details: {
      birthday: "2021-06-22",
      bloodtype: "O",
      club: "野球",
    },
  },
  {
    no: 112,
    lastName: "さの",
    firstName: "あやね",
    gender: "女子",
    grade: 1,
    class: 4,
    lang: 90,
    arith: 82,
    science: 86,
    details: {
      birthday: "2024-10-15",
      bloodtype: "AB",
      club: "なし",
    },
  },
  {
    no: 113,
    lastName: "かとう",
    firstName: "ゆうと",
    gender: "男子",
    grade: 5,
    class: 1,
    lang: 76,
    arith: 94,
    science: 83,
    details: {
      birthday: "2020-02-28",
      bloodtype: "A",
      club: "サッカー",
    },
  },
  {
    no: 114,
    lastName: "たけだ",
    firstName: "ひな",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 69,
    arith: 74,
    science: 71,
  },
  {
    no: 115,
    lastName: "こうの",
    firstName: "さくら",
    gender: "女子",
    grade: 4,
    class: 3,
    lang: 88,
    arith: 92,
    science: 0,
  },
  {
    no: 116,
    lastName: "ふじわら",
    firstName: "りょう",
    gender: "男子",
    grade: 6,
    class: 4,
    lang: 100,
    arith: 99,
    science: 98,
    details: {
      birthday: "2019-03-034",
      bloodtype: "AB",
      club: "水泳",
    },
  },
];
