export const rows = [
  {
    no: 1,
    lastName: "たなか",
    firstName: "はると",
    gender: "男子",
    grade: 3,
    class: 2,
    lang: 82,
    arith: 95,
    science: 78,
  },
  {
    no: 2,
    lastName: "さとう",
    firstName: "あおい",
    gender: "女子",
    grade: 1,
    class: 1,
    lang: 67,
    arith: 73,
    science: 85,
  },
  {
    no: 3,
    lastName: "すずき",
    firstName: "ゆうた",
    gender: "男子",
    grade: 5,
    class: 3,
    lang: 43,
    arith: 50,
    science: 93,
  },
  {
    no: 4,
    lastName: "わたなべ",
    firstName: "みお",
    gender: "女子",
    grade: 2,
    class: 4,
    lang: 79,
    arith: 84,
    science: 43,
  },
  {
    no: 5,
    lastName: "やまもと",
    firstName: "ひなた",
    gender: "女子",
    grade: 4,
    class: 2,
    lang: 88,
    arith: 92,
    science: 89,
  },
  {
    no: 6,
    lastName: "なかむら",
    firstName: "りく",
    gender: "男子",
    grade: 6,
    class: 1,
    lang: 1,
    arith: 42,
    science: 12,
  },
  {
    no: 7,
    lastName: "こばやし",
    firstName: "さくら",
    gender: "女子",
    grade: 3,
    class: 3,
    lang: 76,
    arith: 81,
    science: 74,
  },
  {
    no: 8,
    lastName: "きむら",
    firstName: "そうた",
    gender: "男子",
    grade: 1,
    class: 2,
    lang: 62,
    arith: 69,
    science: 71,
  },
  {
    no: 9,
    lastName: "はやし",
    firstName: "あかり",
    gender: "女子",
    grade: 5,
    class: 4,
    lang: 87,
    arith: 83,
    science: 90,
  },
  {
    no: 10,
    lastName: "さいとう",
    firstName: "ゆうき",
    gender: "男子",
    grade: 2,
    class: 1,
    lang: 67,
    arith: 45,
    science: 53,
  },
  {
    no: 11,
    lastName: "あべ",
    firstName: "みゆ",
    gender: "女子",
    grade: 4,
    class: 3,
    lang: 85,
    arith: 89,
    science: 87,
  },
  {
    no: 12,
    lastName: "うえの",
    firstName: "だいき",
    gender: "男子",
    grade: 6,
    class: 2,
    lang: 93,
    arith: 96,
    science: 94,
  },
  {
    no: 13,
    lastName: "おかだ",
    firstName: "れん",
    gender: "男子",
    grade: 1,
    class: 4,
    lang: 65,
    arith: 71,
    science: 68,
  },
  {
    no: 14,
    lastName: "まつもと",
    firstName: "ななみ",
    gender: "女子",
    grade: 3,
    class: 1,
    lang: 80,
    arith: 86,
    science: 79,
  },
  {
    no: 15,
    lastName: "いのうえ",
    firstName: "はるか",
    gender: "女子",
    grade: 5,
    class: 2,
    lang: 64,
    arith: 91,
    science: 76,
  },
  {
    no: 16,
    lastName: "みやざき",
    firstName: "かずき",
    gender: "男子",
    grade: 2,
    class: 3,
    lang: 75,
    arith: 80,
    science: 77,
  },
  {
    no: 17,
    lastName: "やまだ",
    firstName: "あやか",
    gender: "女子",
    grade: 4,
    class: 4,
    lang: 86,
    arith: 90,
    science: 88,
  },
  {
    no: 18,
    lastName: "おおた",
    firstName: "たくみ",
    gender: "男子",
    grade: 6,
    class: 1,
    lang: 94,
    arith: 100,
    science: 95,
  },
  {
    no: 19,
    lastName: "さの",
    firstName: "ゆい",
    gender: "女子",
    grade: 1,
    class: 2,
    lang: 64,
    arith: 70,
    science: 67,
  },
  {
    no: 20,
    lastName: "こんどう",
    firstName: "しょうた",
    gender: "男子",
    grade: 3,
    class: 4,
    lang: 45,
    arith: 31,
    science: 28,
  },
  {
    no: 21,
    lastName: "いしかわ",
    firstName: "めい",
    gender: "女子",
    grade: 5,
    class: 1,
    lang: 70,
    arith: 63,
    science: 81,
  },
  {
    no: 22,
    lastName: "はしもと",
    firstName: "こうた",
    gender: "男子",
    grade: 2,
    class: 2,
    lang: 74,
    arith: 79,
    science: 76,
  },
  {
    no: 23,
    lastName: "やまぐち",
    firstName: "ひより",
    gender: "女子",
    grade: 4,
    class: 3,
    lang: 87,
    arith: 91,
    science: 89,
  },
  {
    no: 24,
    lastName: "まつだ",
    firstName: "りょう",
    gender: "男子",
    grade: 6,
    class: 4,
    lang: 100,
    arith: 99,
    science: 100,
  },
  {
    no: 25,
    lastName: "いとう",
    firstName: "みなみ",
    gender: "女子",
    grade: 1,
    class: 1,
    lang: 66,
    arith: 72,
    science: 69,
  },
  {
    no: 26,
    lastName: "かとう",
    firstName: "ゆうと",
    gender: "男子",
    grade: 3,
    class: 2,
    lang: 66,
    arith: 68,
    science: 71,
  },
  {
    no: 27,
    lastName: "よしだ",
    firstName: "あいり",
    gender: "女子",
    grade: 5,
    class: 3,
    lang: 88,
    arith: 81,
    science: 83,
  },
  {
    no: 28,
    lastName: "ささき",
    firstName: "はやと",
    gender: "男子",
    grade: 2,
    class: 4,
    lang: 76,
    arith: 81,
    science: 78,
  },
  {
    no: 29,
    lastName: "やまもと",
    firstName: "ゆずき",
    gender: "女子",
    grade: 4,
    class: 1,
    lang: 88,
    arith: 92,
    science: 90,
  },
  {
    no: 30,
    lastName: "いまい",
    firstName: "そうま",
    gender: "男子",
    grade: 6,
    class: 2,
    lang: 33,
    arith: 22,
    science: 11,
  },
  {
    no: 31,
    lastName: "のむら",
    firstName: "ちはる",
    gender: "女子",
    grade: 1,
    class: 3,
    lang: 100,
    arith: 98,
    science: 11,
  },
  {
    no: 32,
    lastName: "ふくだ",
    firstName: "けんと",
    gender: "男子",
    grade: 3,
    class: 4,
    lang: 80,
    arith: 78,
    science: 90,
  },
  {
    no: 33,
    lastName: "にしむら",
    firstName: "まお",
    gender: "女子",
    grade: 5,
    class: 1,
    lang: 93,
    arith: 96,
    science: 94,
  },
  {
    no: 34,
    lastName: "たけうち",
    firstName: "かいと",
    gender: "男子",
    grade: 2,
    class: 2,
    lang: 77,
    arith: 82,
    science: 79,
  },
  {
    no: 35,
    lastName: "なかじま",
    firstName: "りこ",
    gender: "女子",
    grade: 4,
    class: 3,
    lang: 76,
    arith: 90,
    science: 90,
  },
  {
    no: 36,
    lastName: "おくだ",
    firstName: "ゆうすけ",
    gender: "男子",
    grade: 6,
    class: 4,
    lang: 98,
    arith: 99,
    science: 99,
  },
  {
    no: 37,
    lastName: "きくち",
    firstName: "あゆむ",
    gender: "男子",
    grade: 1,
    class: 1,
    lang: 69,
    arith: 75,
    science: 72,
  },
  {
    no: 38,
    lastName: "もり",
    firstName: "はな",
    gender: "女子",
    grade: 3,
    class: 2,
    lang: 0,
    arith: 12,
    science: 34,
  },
  {
    no: 39,
    lastName: "まえだ",
    firstName: "りん",
    gender: "女子",
    grade: 5,
    class: 3,
    lang: 94,
    arith: 97,
    science: 95,
  },
  {
    no: 40,
    lastName: "はら",
    firstName: "こうせい",
    gender: "男子",
    grade: 2,
    class: 4,
    lang: 78,
    arith: 71,
    science: 55,
  },
  {
    no: 41,
    lastName: "えんどう",
    firstName: "みさき",
    gender: "女子",
    grade: 4,
    class: 1,
    lang: 90,
    arith: 94,
    science: 92,
  },
  {
    no: 42,
    lastName: "あらい",
    firstName: "だいち",
    gender: "男子",
    grade: 6,
    class: 2,
    lang: 99,
    arith: 100,
    science: 100,
  },
  {
    no: 43,
    lastName: "おの",
    firstName: "なな",
    gender: "女子",
    grade: 1,
    class: 3,
    lang: 97,
    arith: 36,
    science: 83,
  },
  {
    no: 44,
    lastName: "こばやし",
    firstName: "そら",
    gender: "男子",
    grade: 3,
    class: 4,
    lang: 86,
    arith: 91,
    science: 88,
  },
  {
    no: 45,
    lastName: "ふじた",
    firstName: "ゆうひ",
    gender: "女子",
    grade: 5,
    class: 1,
    lang: 95,
    arith: 98,
    science: 96,
  },
  {
    no: 46,
    lastName: "みやた",
    firstName: "るい",
    gender: "男子",
    grade: 2,
    class: 2,
    lang: 79,
    arith: 84,
    science: 81,
  },
  {
    no: 47,
    lastName: "ごとう",
    firstName: "あおば",
    gender: "男子",
    grade: 4,
    class: 3,
    lang: 91,
    arith: 95,
    science: 100,
  },
  {
    no: 48,
    lastName: "かわぐち",
    firstName: "ひろと",
    gender: "男子",
    grade: 6,
    class: 4,
    lang: 100,
    arith: 99,
    science: 100,
  },
  {
    no: 49,
    lastName: "はやし",
    firstName: "ゆな",
    gender: "女子",
    grade: 1,
    class: 1,
    lang: 71,
    arith: 100,
    science: 74,
  },
  {
    no: 50,
    lastName: "やまもと",
    firstName: "たいが",
    gender: "男子",
    grade: 3,
    class: 2,
    lang: 87,
    arith: 92,
    science: 89,
  },
  {
    no: 51,
    lastName: "むらた",
    firstName: "さや",
    gender: "女子",
    grade: 5,
    class: 3,
    lang: 96,
    arith: 99,
    science: 97,
  },
  {
    no: 52,
    lastName: "うえだ",
    firstName: "りょうた",
    gender: "男子",
    grade: 2,
    class: 4,
    lang: 50,
    arith: 45,
    science: 82,
  },
  {
    no: 53,
    lastName: "あおき",
    firstName: "まひろ",
    gender: "女子",
    grade: 4,
    class: 1,
    lang: 92,
    arith: 96,
    science: 94,
  },
  {
    no: 54,
    lastName: "なかの",
    firstName: "とうま",
    gender: "男子",
    grade: 6,
    class: 2,
    lang: 99,
    arith: 100,
    science: 99,
  },
  {
    no: 55,
    lastName: "こんどう",
    firstName: "あんな",
    gender: "女子",
    grade: 1,
    class: 3,
    lang: 72,
    arith: 78,
    science: 75,
  },
  {
    no: 56,
    lastName: "おおつか",
    firstName: "ゆうご",
    gender: "男子",
    grade: 3,
    class: 4,
    lang: 88,
    arith: 93,
    science: 90,
  },
];
